name: Website Frontend Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: 🛠 Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/website:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/website:${{ github.sha }} .

      - name: 🚀 Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/website:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/website:${{ github.sha }}

      - name: 🖥️ Deploy to Server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            echo "🔐 Connected to production server"
            
            cd /home/million/mrbeas || exit 1
            
            echo "⬇️ Pulling latest website image..."
            docker-compose pull website
            
            echo "🔄 Updating website service..."
            docker-compose up -d --no-deps website
            
            echo "🔄 Reloading Caddy reverse proxy..."
            docker exec caddy_reverse_proxy caddy reload
            
            echo "🧹 Cleaning old images..."
            docker image prune -af --filter "until=24h"
            
            echo "✅ Website deployment complete!"
          EOF